---
api_version: "2"
image: "centos/8"
ip_part: "192.160.0"
user: "vagrant"

cluster:
    master: "mssql"

resources:
    master:
        cpus: 2
        memory: 2048
        root_password: 123
        user: anand
        password: 123

net:
    network_type: private_network
