---
api_version: "2"
image: "ubuntu/focal64"
ip_part: "192.168.56"
user: "vagrant"

cluster:
    master: "grafana"

resources:
    master:
        cpus: 2
        memory: 2048
        root_password: 123
        user: anand
        password: 123

net:
    network_type: private_network
