# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'open3'

k8s = YAML.load_file(File.join(File.dirname(__FILE__), 'config.yaml'))
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(k8s['api_version']) do |config|
	config.vm.boot_timeout = 600

    config.vm.define "#{k8s['cluster']['master']}" do |subconfig|
        subconfig.vm.post_up_message = $msg
        subconfig.vm.box = k8s['image']
        subconfig.vm.box_check_update = false

        subconfig.vm.hostname = "#{k8s['cluster']['master']}"
        subconfig.vm.network :private_network, ip: "#{k8s['ip_part']}.10"

        subconfig.vm.provider "virtualbox" do |vb|
            vb.memory = k8s['resources']['master']['memory']
            vb.cpus = k8s['resources']['master']['cpus']
        end

        subconfig.vm.provision "Enable Firewall", type: "shell" do |enable_firewall|
            enable_firewall.inline = <<-SHELL
                apt update
                echo debconf mysql-server/root_password password #{k8s['resources']['master']['root_password']} | sudo debconf-set-selections
                echo debconf mysql-server/root_password_again password #{k8s['resources']['master']['root_password']} | sudo debconf-set-selections
                apt-get install mysql-server expect -y
                # sudo mysql_secure_installation
                ufw enable
                ufw allow mysql

                sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/my.cnf
                service mysql enable
                mysql -e "CREATE USER '#{k8s['resources']['master']['user']}'@'%' IDENTIFIED BY '#{k8s['resources']['master']['password']}';" -p#{k8s['resources']['master']['root_password']}
                mysql -e "GRANT ALL PRIVILEGES ON *.* TO '#{k8s['resources']['master']['user']}'@'%';" -p#{k8s['resources']['master']['root_password']}
            SHELL
        end

        subconfig.vm.provision "Reboot to load all config", type:"shell", inline: "shutdown -r now"
    end
end
